"""fix bugs

Revision ID: c80a464b5691
Revises: 10faf3814a61
Create Date: 2025-05-10 15:06:39.893636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c80a464b5691'
down_revision: Union[str, None] = '10faf3814a61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('startup', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_constraint('startup_author_fkey', 'startup', type_='foreignkey')
    op.create_foreign_key(None, 'startup', 'users', ['author_id'], ['id'], ondelete='cascade')
    op.drop_column('startup', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('startup', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'startup', type_='foreignkey')
    op.create_foreign_key('startup_author_fkey', 'startup', 'users', ['author'], ['id'], ondelete='CASCADE')
    op.drop_column('startup', 'author_id')
    # ### end Alembic commands ###
